name: GitHub Actions Demo
on: 
  pull_request:
    branches:
      - "**"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Showing message
      - uses: actions/checkout@v2
      - run: echo "🎉 A PR has created."
